version: '3.9'

services:
  api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/ticketdb
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elastic
      - ELASTIC_CA_PATH=/usr/config/certs/http_ca.crt
    volumes:
      - ./api:/usr/src
      - ./api/config/certs/http_ca.crt:/usr/config/certs/http_ca.crt
    networks:
      - ticketmaster_net

  web:
    build:
      context: ./web
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    depends_on:
      - api
    networks:
      - ticketmaster_net

networks:
  ticketmaster_net:
    external: true
